### ISSUE TITLE
OAuth token?

### ISSUE THREAD

**Issue by Ruriko** [aswinnnn/weheartit-api#1]
do you know how to get the oauth token?

**Comment by ohaswin** [comment]
weheartit uses a signature to login every account using OAuth. This signature is unique to every account and is an md5 encrypt from various things. I've tried to find the signature method but currently I have no information regarding how the authentication would work outside the app aka in our code. 

The request would look something like this: 
```python
import requests


def login(self, username: str, password: str):
    data = {
          "username": username,
          "password": password,
            "signature": "ea7a150d4e8fa38a99f0d86fdbb",
            "grant_type": "password"
          }
    response = requests.post(
           f"{self.api}/oauth/token",
            data=data,
            headers=self.headers).json()
    if "access_token" in response:
        self.access_token = response["access_token"]
        self.headers["authorization"] = f"Bearer {self.access_token}"
        return response

login("username", "password")

```
But getting the authentication to work doesn't seem possible at this time.
